[goerli]
consensus_rpc = "http://testing.prater.beacon-api.nimbus.team"
execution_rpc = "https://goerli.infura.io/v3/{INFURA_KEY}"
load_external_fallback = true
data_dir = "./data/goerli"
checkpoint = "0x3afa740d93317ba849fa3527c5bfc51b3fd63f28d4763773b052a563fb97acb4"

[sepolia]
consensus_rpc = "http://unstable.sepolia.beacon-api.nimbus.team"
execution_rpc = "https://sepolia.infura.io/v3/{INFURA_KEY}"
load_external_fallback = true
data_dir = "./data/sepolia"
checkpoint = "0xc6203ac1c054548242b7710b1ef67f1b912e52cd34afe133865f07ce1218811a"
fallback = "https://beaconstate-sepolia.chainsafe.io/"
