[goerli]
consensus_rpc = "http://testing.prater.beacon-api.nimbus.team"
execution_rpc = "https://goerli.infura.io/v3/{INFURA_KEY}"
load_external_fallback = true
data_dir = "./data/goerli"
checkpoint = ""
